obj-$(CONFIG_MULTI_KERNELSU) += ksu_bridge.o

obj-$(CONFIG_KSU_NEXT)       += ksunext/
obj-$(CONFIG_KSU_RKSU)       += rksu/
obj-$(CONFIG_KSU_RESUKISU)+= resukisu/
obj-$(CONFIG_KSU_XXKSU)      += xxksu/